services:
  - type: web
    name: websocket-collab-drawing
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CLIENT_ORIGIN
        value: https://ducmtran-commit.github.io
